<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0282fffd-743f-4e95-b657-6beff38d9a5e</testSuiteGuid>
   <testCaseLink>
      <guid>c912d3e2-3065-4f34-93f6-f00925049490</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eaab5616-c76d-4c5e-9560-a14d2d9fda46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f01f30e7-400f-4dd6-bf76-8f86919b7982</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b183491-5624-4a3e-bfd5-a2dee51f584a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff6a5999-27fe-4efa-84ab-42389e26ae8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>659eef00-6eb0-4e1d-a526-798a5cdcac64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87bccf96-9e9f-4d93-a443-f6abe7261dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d2d48b2-0f72-431e-a790-16d2c817780f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36217a73-d158-4258-aa4f-60310bbe9864</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7397e100-0cf8-46ef-b81b-b61034332f12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e83cb42-ce2a-4057-a162-305a8d268500</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>000125d0-efde-4b05-8518-d5a8a62cbeb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27a38d48-21a8-4764-976f-5480f7156fa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06e93f03-f26d-492b-8b4d-2617be5bfd3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>113979a1-2896-42a9-968d-813cc412a2fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e2aa4cb7-94c1-451b-9858-849ca1621c96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c83484d-09e5-4da1-bb20-f95be97137bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04d934bc-9b4c-4a42-ad2e-54028dbf0c9f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b72b022a-519b-4e52-a96f-b27c436b2b18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce36b1a5-db88-4f1e-86ab-054ff96a1217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>108ec9c3-8fe9-4716-88fc-434a8c5f8e10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb67ced0-acef-4d15-b9bd-8dbbabd46d10</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d506f80-d1b4-4cf6-81e8-9ddcaec838af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab13ae1d-39a7-46ae-9dd0-c5759df6dcb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e471e17-b129-4805-a50c-03d7ee20f4ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e58291df-7249-4daf-9cda-1267fbbf016f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebc14635-ef50-4196-b173-5e1de787eeeb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1ec88af-5c43-4ae2-af7d-4d36530d7441</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1906066f-b3f8-4823-9ccc-404921c613de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>182ed2d9-4cee-4ef7-8060-6d70166d0a3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7305b791-fce4-4b58-86f2-c198332f57b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28597734-085c-4bfd-b6a7-314022a2bc94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>791dae41-d314-47d5-87c5-54e4712cbb4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86ef2fed-6071-461e-a5b3-f6ed26b80daa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>246cfd3f-858e-43da-8178-34b8739990d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9882e118-65ed-4c80-9910-f026b0884592</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0ca4327-7bf0-4145-9c8f-b190eee1e33c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04c3d308-545d-44bc-b077-142775577f24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1dac932-ea86-4d90-80b6-ba155a4be3c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80e70d7e-0149-47c0-80af-7534359c4bdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfbcf3b0-75c9-42fd-a110-e7680c8e13b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e145218-7877-4cc3-aa15-07334b0ed124</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbd963ba-3b24-4467-b116-a30a3300fd21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51cbc3b3-49d2-47b2-8b07-a7f0bca68be2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21207e86-706b-42ac-9f74-45f3d56ccd8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ff3a88a7-cdf6-4d26-8b7f-9e89962da66c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 6</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e2fa06a-a618-4ae2-a362-e125c801cc11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>def7af55-b51a-43bb-87bf-19e8c684731d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7cc23fd-6cae-4165-bbb7-050758492d32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32d8fa63-783e-460e-9934-f942b7871787</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a0dca44-bb3f-46f7-846e-3923d1c5b1e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d89a5d53-5d24-400f-9f04-22323896b00e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0505424b-37e7-46d5-beb2-82fe3a76bf1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fdd3dfa-30b4-4c20-8225-60be92913590</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5c7ad53-6c79-4b3d-a80c-b4745e045528</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 7</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f126e654-228c-4952-928b-9eba707175fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82dd16c4-cb76-4609-b646-b81fd2b44cf4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61c9d6f5-dc3d-42ed-8782-6823844c2a90</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>169b3360-2377-49b9-9fd3-5ed78a66e371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a51a009b-6bff-4ab2-8b1f-951515146731</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95bdb21d-9460-4972-a3d1-ec4b6d8a7517</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ebd468e-5a00-4a52-8773-d42161f34a39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a6a83d2-b42d-439f-929a-abfd74a42e51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c3f224a-c67e-4c7f-88b8-9c95aeaf2427</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 8</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45f9ead7-b38b-4492-aef1-d9b2322fa3b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a47096c3-603b-41a2-a430-070533a254a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bc7d816-a469-4f72-94e8-a964e65d17e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e500e1a-8eb7-4c82-b1e6-781290e23a5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a8ee92c-9513-40a2-9ac1-edf4a0a2cf75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36225b4d-8603-43aa-8254-e85610c0a4ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce032f66-30c2-4890-9443-5915af46168f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79f957f6-058e-48f0-a449-a8c8e19ad8f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4454383d-745c-4948-b255-b6432ce6383e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray 9</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90984589-3dd4-4555-b6f1-d44f613ff7bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d503b16-0a10-4252-89ab-5a60a617c27b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d127dc7c-e143-458b-a214-aa50708b9fb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4f755dc-9c8b-43bc-b655-e479d878db9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0341277b-61b3-4d45-8570-ba36f09dd6f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f1cd3f0-8ba7-4fcf-9ff7-7ae0676368b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24311357-74a0-40b3-9dac-5eab90147251</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a557abd-c5f3-4535-9c0a-c79826043b05</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b8caeb6-4564-4d30-aa51-623085ed9d39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Custom-keyword samples/Auto-attach PDF Reports to Xray Test Execution after pushing Test Run to Xray</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>700d6e4e-307e-448a-aa19-8127c96f0056</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c0d16db-73f9-40b6-851f-f777b8bae206</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>672fb4fd-4f00-452f-a8b4-62df3d124ffc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51421ccf-ad17-4e9f-9d5a-18e620ee93bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c863fc5-9dab-4c4a-881c-d478032e26c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f8f1ad7-8f79-44a0-b33d-fc78e90e9e1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1106ce6b-eba2-406b-ac41-b29f53a45fcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cb399d2-1bfc-408e-8254-a03dd003f568</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
